services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c max_connections=100
    networks:
      - payment-network
  payment-server:
    build:
      context: .
      dockerfile: payment_server/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - payment-network

  payment-client:
    build:
      context: .
      dockerfile: payment_client/Dockerfile
    depends_on:
      - payment-server
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge