// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: mock_payment/mock_payment.proto

package mockPayment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // "100500.0 USD"
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_mock_payment_mock_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mock_payment_mock_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_mock_payment_mock_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *PaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_mock_payment_mock_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mock_payment_mock_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_mock_payment_mock_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PaymentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mock_payment_mock_payment_proto protoreflect.FileDescriptor

const file_mock_payment_mock_payment_proto_rawDesc = "" +
	"\n" +
	"\x1fmock_payment/mock_payment.proto\x12\vmockPayment\"a\n" +
	"\x0ePaymentRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"W\n" +
	"\x0fPaymentResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2]\n" +
	"\x0ePaymentService\x12K\n" +
	"\x0eProcessPayment\x12\x1b.mockPayment.PaymentRequest\x1a\x1c.mockPayment.PaymentResponseB\x0fZ\r.;mockPaymentb\x06proto3"

var (
	file_mock_payment_mock_payment_proto_rawDescOnce sync.Once
	file_mock_payment_mock_payment_proto_rawDescData []byte
)

func file_mock_payment_mock_payment_proto_rawDescGZIP() []byte {
	file_mock_payment_mock_payment_proto_rawDescOnce.Do(func() {
		file_mock_payment_mock_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_payment_mock_payment_proto_rawDesc), len(file_mock_payment_mock_payment_proto_rawDesc)))
	})
	return file_mock_payment_mock_payment_proto_rawDescData
}

var file_mock_payment_mock_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mock_payment_mock_payment_proto_goTypes = []any{
	(*PaymentRequest)(nil),  // 0: mockPayment.PaymentRequest
	(*PaymentResponse)(nil), // 1: mockPayment.PaymentResponse
}
var file_mock_payment_mock_payment_proto_depIdxs = []int32{
	0, // 0: mockPayment.PaymentService.ProcessPayment:input_type -> mockPayment.PaymentRequest
	1, // 1: mockPayment.PaymentService.ProcessPayment:output_type -> mockPayment.PaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_payment_mock_payment_proto_init() }
func file_mock_payment_mock_payment_proto_init() {
	if File_mock_payment_mock_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_payment_mock_payment_proto_rawDesc), len(file_mock_payment_mock_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mock_payment_mock_payment_proto_goTypes,
		DependencyIndexes: file_mock_payment_mock_payment_proto_depIdxs,
		MessageInfos:      file_mock_payment_mock_payment_proto_msgTypes,
	}.Build()
	File_mock_payment_mock_payment_proto = out.File
	file_mock_payment_mock_payment_proto_goTypes = nil
	file_mock_payment_mock_payment_proto_depIdxs = nil
}
